import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Download, Music, Loader2, ShoppingCart, FileText, Mic } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import type { NoteEvent } from "@/lib/types";

interface ExportPanelProps {
  notes: NoteEvent[];
  scoreId: number | null;
  onSaveScore: (notes: NoteEvent[]) => Promise<number | null>;
  variant?: "desktop" | "mobile";
  scoreTitle?: string;
  artistName?: string;
  audioBlob?: Blob | null;
}

const FORMATS = [
  { id: "musicxml" as const, label: "MusicXML", price: 0.99, icon: Download, description: "For notation software" },
  { id: "midi" as const, label: "MIDI", price: 1.99, icon: Music, description: "For DAWs & production" },
];

async function downloadPdf(scoreTitle: string, artistName: string) {
  const staffContainer = document.querySelector('[data-testid="staff-container"]');
  if (!staffContainer) {
    throw new Error("No sheet music found to export");
  }

  const svgEl = staffContainer.querySelector("svg");
  if (!svgEl) {
    throw new Error("No sheet music found to export");
  }

  const { jsPDF } = await import("jspdf");
  const { svg2pdf } = await import("svg2pdf.js");

  const svgWidth = svgEl.viewBox.baseVal.width || svgEl.clientWidth || 700;
  const svgHeight = svgEl.viewBox.baseVal.height || svgEl.clientHeight || 400;

  const pdfWidth = 210;
  const margin = 15;
  const contentWidth = pdfWidth - margin * 2;
  const scale = contentWidth / svgWidth;
  const scaledHeight = svgHeight * scale;

  const pdfHeight = Math.max(297, scaledHeight + 60 + margin);
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: [pdfWidth, pdfHeight] });

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(scoreTitle || "Untitled Score", pdfWidth / 2, margin + 10, { align: "center" });

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Transcribed by ${artistName || "Baseline User"}`, pdfWidth / 2, margin + 18, { align: "center" });

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Baseline", pdfWidth / 2, margin + 24, { align: "center" });
  doc.setTextColor(0);

  const clonedSvg = svgEl.cloneNode(true) as SVGElement;
  clonedSvg.querySelectorAll("*").forEach((el) => {
    const fill = (el as SVGElement).style?.fill || el.getAttribute("fill");
    const stroke = (el as SVGElement).style?.stroke || el.getAttribute("stroke");
    if (fill && fill !== "none" && fill !== "transparent") {
      (el as SVGElement).style.fill = "#1a1a1a";
    }
    if (stroke && stroke !== "none" && stroke !== "transparent") {
      (el as SVGElement).style.stroke = "#1a1a1a";
    }
  });

  if (!clonedSvg.getAttribute("viewBox")) {
    clonedSvg.setAttribute("viewBox", `0 0 ${svgWidth} ${svgHeight}`);
  }
  clonedSvg.setAttribute("width", `${svgWidth}`);
  clonedSvg.setAttribute("height", `${svgHeight}`);

  await svg2pdf(clonedSvg, doc, {
    x: margin,
    y: margin + 30,
    width: contentWidth,
    height: scaledHeight,
  });

  doc.save(`${(scoreTitle || "baseline-score").replace(/\s+/g, "-").toLowerCase()}.pdf`);
}

function downloadRecording(audioBlob: Blob, scoreTitle: string) {
  const ext = audioBlob.type.includes("mp4") ? "m4a" : audioBlob.type.includes("ogg") ? "ogg" : "webm";
  const filename = `${(scoreTitle || "baseline-recording").replace(/\s+/g, "-").toLowerCase()}.${ext}`;
  const url = URL.createObjectURL(audioBlob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ExportPanel({ notes, scoreId, onSaveScore, variant = "desktop", scoreTitle = "Untitled Score", artistName = "Baseline User", audioBlob }: ExportPanelProps) {
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [isCheckingOut, setIsCheckingOut] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const { toast } = useToast();

  const toggleFormat = (formatId: string) => {
    setSelected(prev => {
      const next = new Set(prev);
      if (next.has(formatId)) {
        next.delete(formatId);
      } else {
        next.add(formatId);
      }
      return next;
    });
  };

  const subtotal = FORMATS.filter(f => selected.has(f.id)).reduce((sum, f) => sum + f.price, 0);
  const hasSelection = selected.size > 0;
  const hasNotes = notes.length > 0;

  const handleCheckout = async () => {
    if (!hasSelection || !hasNotes) return;

    let id = scoreId;
    if (!id) {
      id = await onSaveScore(notes);
      if (!id) {
        toast({ title: "Please record some notes first", variant: "destructive" });
        return;
      }
    }

    setIsCheckingOut(true);
    try {
      const formats = Array.from(selected);
      const res = await fetch(`/api/scores/${id}/checkout`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ formats }),
      });

      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || "Checkout failed");
      }

      const { url } = await res.json();
      if (url) {
        window.location.href = url;
      }
    } catch (err: any) {
      toast({ title: err.message || "Checkout failed", variant: "destructive" });
    } finally {
      setIsCheckingOut(false);
    }
  };

  const handlePdfDownload = async () => {
    setIsGeneratingPdf(true);
    try {
      await downloadPdf(scoreTitle, artistName);
      toast({ title: "PDF downloaded!" });
    } catch (err) {
      console.error("PDF generation error:", err);
      toast({ title: "PDF generation failed", variant: "destructive" });
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleRecordingDownload = () => {
    if (!audioBlob) return;
    downloadRecording(audioBlob, scoreTitle);
    toast({ title: "Recording downloaded!" });
  };

  const freeButtons = (
    <div className={variant === "mobile" ? "flex gap-2" : "space-y-1.5"}>
      <Button
        variant="outline"
        size="sm"
        className={`gap-2 text-xs ${variant === "mobile" ? "flex-1" : "w-full"}`}
        onClick={handlePdfDownload}
        disabled={!hasNotes || isGeneratingPdf}
        data-testid="button-download-pdf"
      >
        {isGeneratingPdf ? <Loader2 className="h-3 w-3 animate-spin" /> : <FileText className="h-3 w-3" />}
        {isGeneratingPdf ? "Generating..." : "PDF"}
        <span className="text-green-500 font-semibold ml-auto">FREE</span>
      </Button>
      <Button
        variant="outline"
        size="sm"
        className={`gap-2 text-xs ${variant === "mobile" ? "flex-1" : "w-full"}`}
        onClick={handleRecordingDownload}
        disabled={!audioBlob}
        data-testid="button-download-recording"
      >
        <Mic className="h-3 w-3" />
        Audio
        <span className="text-green-500 font-semibold ml-auto">FREE</span>
      </Button>
    </div>
  );

  if (variant === "mobile") {
    return (
      <div className="space-y-2 px-4 py-3 border-t border-border/30">
        <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground text-center">Export</p>

        <p className="text-[10px] text-muted-foreground/60 uppercase tracking-wider text-center">Free Downloads</p>
        {freeButtons}

        <div className="border-t border-border/20 pt-2 mt-2">
          <p className="text-[10px] text-muted-foreground/60 uppercase tracking-wider text-center mb-2">Premium Formats</p>
          <div className="space-y-2">
            {FORMATS.map(f => (
              <label
                key={f.id}
                className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer transition-all ${
                  selected.has(f.id)
                    ? "border-primary bg-primary/10"
                    : "border-border/50 bg-muted/20 hover:border-border"
                } ${!hasNotes ? "opacity-40 pointer-events-none" : ""}`}
                data-testid={`checkbox-export-${f.id}`}
              >
                <Checkbox
                  checked={selected.has(f.id)}
                  onCheckedChange={() => toggleFormat(f.id)}
                  disabled={!hasNotes}
                />
                <f.icon className="h-4 w-4 text-muted-foreground" />
                <div className="flex-1">
                  <span className="text-sm font-medium">{f.label}</span>
                  <span className="text-[10px] text-muted-foreground block">{f.description}</span>
                </div>
                <span className="text-sm font-mono text-primary">${f.price.toFixed(2)}</span>
              </label>
            ))}
          </div>

          {hasSelection && (
            <div className="space-y-2 animate-in slide-in-from-bottom-2 duration-200 mt-2">
              <div className="flex justify-between items-center px-1 pt-1">
                <span className="text-xs text-muted-foreground uppercase tracking-wider">Subtotal</span>
                <span className="text-lg font-mono font-bold text-primary" data-testid="text-subtotal">${subtotal.toFixed(2)}</span>
              </div>
              <Button
                className="w-full gap-2"
                size="lg"
                onClick={handleCheckout}
                disabled={isCheckingOut || !hasNotes}
                data-testid="button-checkout"
              >
                {isCheckingOut ? (
                  <><Loader2 className="h-4 w-4 animate-spin" /> Processing...</>
                ) : (
                  <><ShoppingCart className="h-4 w-4" /> Checkout</>
                )}
              </Button>
            </div>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Export</p>

      <div className="space-y-1">
        <p className="text-[10px] text-muted-foreground/60 uppercase tracking-wider">Free Downloads</p>
        {freeButtons}
      </div>

      <div className="border-t border-border/20 pt-3">
        <p className="text-[10px] text-muted-foreground/60 uppercase tracking-wider mb-2">Premium Formats</p>
        <div className="space-y-2">
          {FORMATS.map(f => (
            <label
              key={f.id}
              className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer transition-all ${
                selected.has(f.id)
                  ? "border-primary bg-primary/10"
                  : "border-border/50 bg-muted/20 hover:border-border"
              } ${!hasNotes ? "opacity-40 pointer-events-none" : ""}`}
              data-testid={`checkbox-export-${f.id}`}
            >
              <Checkbox
                checked={selected.has(f.id)}
                onCheckedChange={() => toggleFormat(f.id)}
                disabled={!hasNotes}
              />
              <f.icon className="h-4 w-4 text-muted-foreground" />
              <div className="flex-1 min-w-0">
                <span className="text-sm font-medium">{f.label}</span>
                <span className="text-[10px] text-muted-foreground block">{f.description}</span>
              </div>
              <span className="text-sm font-mono text-primary">${f.price.toFixed(2)}</span>
            </label>
          ))}
        </div>

        {hasSelection && (
          <div className="space-y-2 animate-in slide-in-from-bottom-2 duration-200 mt-2">
            <div className="flex justify-between items-center px-1">
              <span className="text-xs text-muted-foreground uppercase tracking-wider">Subtotal</span>
              <span className="text-lg font-mono font-bold text-primary" data-testid="text-subtotal">${subtotal.toFixed(2)}</span>
            </div>
            <Button
              className="w-full gap-2"
              size="lg"
              onClick={handleCheckout}
              disabled={isCheckingOut || !hasNotes}
              data-testid="button-checkout"
            >
              {isCheckingOut ? (
                <><Loader2 className="h-4 w-4 animate-spin" /> Processing...</>
              ) : (
                <><ShoppingCart className="h-4 w-4" /> Checkout</>
              )}
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
